### ISSUE TITLE
Sequence semantics

### ISSUE THREAD

**Issue by odnoletkov** [NSHipster/Cycle#1]
I think there are two possible problems with Sequence semantics in the current implementation:
1. Sequences don't guarantee non-destructive iteration, so in general you can't iterate them multiple times: [Repeated Access](https://developer.apple.com/documentation/swift/sequence)
2. It is often useful to have implementation supporting infinite sequences. While this is not a strict requirement from the protocol it may be useful in contexts where finiteness of sequences is unknown.

I've sketched up this version confirming to both of these requirements:
```swift
extension Sequence {
    var cycled: AnySequence<Element> {
        var buffer: [Element] = []
        return AnySequence(
            [
                AnySequence(lazy.map { buffer.append($0); return $0 }),
                AnySequence(AnyIterator { buffer }.joined())
                ].joined()
        )
    }
}
```

It's a shame `JoinedSequence` doesn't handle infinite `separator` case properly, or this could be even further simplified by using infinite buffer repetitions as separator.

**Comment by mattt** [comment]
Fortunately, this is now provided by `swift-algorithms`: https://github.com/apple/swift-algorithms/blob/main/Guides/Cycle.md
